# Generated by Django 2.2.4 on 2025-10-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authors_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='first_name',
            new_name='titel',
        ),
    ]
