# Generated by Django 2.2.4 on 2025-10-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20251008_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='notes',
            new_name='desc',
        ),
    ]
