# Generated by Django 2.2.4 on 2025-10-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251008_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='titel',
            new_name='first_name',
        ),
    ]
