# Generated by Django 2.2.4 on 2025-10-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='aubdated_at',
            new_name='updated_at',
        ),
    ]
